<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <li class="disabled">
            <a>
                Exibindo
                <?php echo $this->firstItemNumber; ?> a <?php echo $this->lastItemNumber; ?>
                de
                <?php echo $this->totalItemCount; ?> 
                registros
            </a>
        </li>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php
                echo $this->url($this->route, array(), array(
                    'query' => array_merge(
                            (array) $this->getHelperPluginManager()->getServiceLocator()->get('Request')->getQuery(), array('page' => $this->previous) // must be before to override 'page' index
                    )), true);
                ?>">
                    <<
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a href="#">
                    <<
                </a>
            </li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php
                    echo $this->url($this->route, array(), array(
                        'query' => array_merge(
                                (array) $this->getHelperPluginManager()->getServiceLocator()->get('Request')->getQuery(), array('page' => $page) // must be before to override 'page' index
                        )), true);
                    ?>">
                           <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php
                echo $this->url($this->route, array(), array(
                    'query' => array_merge(
                            (array) $this->getHelperPluginManager()->getServiceLocator()->get('Request')->getQuery(), array('page' => $this->next) // must be before to override 'page' index
                    )), true);
                ?>">
                    >>
                </a>
            </li>
    <?php else: ?>
            <li class="disabled">
                <a href="#">
                    >>
                </a>
            </li>
    <?php endif; ?>
    </ul>
<?php endif; ?>
